### ISSUE TITLE
Running prebuilt container image via podman fails with: RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by slaudel** [ngandrass/moodle-quiz-archive-worker#1]
I'm using podman instead of docker and was trying to run the moodle quiz archiver container but this fails with the following error:
```
podman run -it --rm  --name moodlequizarchiver -p 8080:8080 docker.io/ngandrass/moodle-quiz-archive-worker
```
```
[2023-08-16 09:56:14,043] | INFO     | moodle-quiz-archive-worker | Running moodle-quiz-archive-worker version 1.0.6 on log level INFO
Traceback (most recent call last):
  File "/app/moodle-quiz-archive-worker.py", line 208, in <module>
    main()
  File "/app/moodle-quiz-archive-worker.py", line 202, in main
    queue_processing_thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by ngandrass** [comment]
Thanks for your bug report! I never tried running this image on podman before. A quick search indicated, that your container might be missing the permission to execute the `clone3` syscall. Please verify that this is allowed inside your seccomp profile.

This is the podman issue I found regarding this problem: https://github.com/containers/podman/issues/11862

**Comment by ngandrass** [comment]
Same problem, other bug report. Comment 2 contains methods to debug which syscalls are blocked :) https://bugzilla.redhat.com/show_bug.cgi?id=1985499#c2

**Comment by slaudel** [comment]
> Same problem, other bug report. Comment 2 contains methods to debug which syscalls are blocked :) https://bugzilla.redhat.com/show_bug.cgi?id=1985499#c2
> 
> You can also try to run the container without any seccomp restrictions, to confirm that seccomp causes this issue, by adding `--security-opt seccomp=unconfined`:
> 
> ```
> podman run --security-opt seccomp=unconfined -it --rm  --name moodlequizarchiver -p 8080:8080 docker.io/ngandrass/moodle-quiz-archive-worker
> ```

Yes, that was the problem.

**Comment by slaudel** [comment]
Seems like the following seccomp policy solves the problem.

```
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "architectures": [
    "SCMP_ARCH_X86_64"
  ],
  "syscalls": [
    {
      "names": [
        "accept4",
        "access",
        "arch_prctl",
        "bind",
        "brk",
        "capget",
        "capset",
        "chdir",
        "chmod",
        "clock_gettime",
        "clock_nanosleep",
        "clone",
        "clone3",
        "close",
        "close_range",
        "connect",
        "creat",
        "dup",
        "dup2",
        "dup3",
        "epoll_create",
        "epoll_create1",
        "epoll_ctl",
        "epoll_pwait",
        "epoll_wait",
        "eventfd2",
        "execve",
        "exit",
        "exit_group",
        "faccessat2",
        "fadvise64",
        "fallocate",
        "fchown",
        "fcntl",
        "fdatasync",
        "fstat",
        "fstatfs",
        "ftruncate",
        "futex",
        "getcwd",
        "getdents64",
        "getegid",
        "geteuid",
        "getgid",
        "getpeername",
        "getpgrp",
        "getpid",
        "getppid",
        "getpriority",
        "getrandom",
        "getresgid",
        "getresuid",
        "getsockname",
        "getsockopt",
        "gettid",
        "getuid",
        "inotify_add_watch",
        "inotify_init",
        "ioctl",
        "kill",
        "link",
        "listen",
        "lseek",
        "lstat",
        "madvise",
        "mkdir",
        "mmap",
        "mprotect",
        "mremap",
        "munmap",
        "name_to_handle_at",
        "nanosleep",
        "newfstatat",
        "openat",
        "pipe2",
        "poll",
        "ppoll",
        "prctl",
        "pread64",
        "prlimit64",
        "pselect6",
        "pwrite64",
        "read",
        "readlink",
        "recvfrom",
        "recvmsg",
        "rename",
        "rmdir",
        "rseq",
        "rt_sigaction",
        "rt_sigprocmask",
        "rt_sigreturn",
        "sched_getaffinity",
        "sched_setaffinity",
        "sendmmsg",
        "sendmsg",
        "sendto",
        "set_robust_list",
        "set_tid_address",
        "setgid",
        "setgroups",
        "setpriority",
        "setsid",
        "setsockopt",
        "setuid",
        "shutdown",
        "socket",
        "socketpair",
        "stat",
        "statfs",
        "statx",
        "sysinfo",
        "tgkill",
        "umask",
        "uname",
        "unlink",
        "unlinkat",
        "vfork",
        "wait4",
        "write",
        "writev"
      ],
      "action": "SCMP_ACT_ALLOW",
      "args": [],
      "comment": "",
      "includes": {},
      "excludes": {}
    }
  ]
}
```

Put it into a file and and the following to the podman run command `--security-opt seccomp=./FILE_WITH_POLICY.json`
e. g. `podman run -it --rm --security-opt seccomp=./moodle-quiz-archiver3.json --name moodlequizarchiver -p 8080:8080 docker.io/ngandrass/moodle-quiz-archive-worker`

**Comment by ngandrass** [comment]
Thanks for contributing your seccomp config :tada: 

I changed the issue title to "Running prebuilt container image via podman fails with: RuntimeError: can't start new thread" to make if easier to find for other people that might run into this problem.
